### ISSUE TITLE
Feature Request: onWithOptions

### ISSUE THREAD

**Issue by jinjor** [elm-lang/dom#1]
I need the same thing as `Html.Events.onWithOptions`.

Now I am implementing a keyboard shortcut `ctrl+A` for selecting all objects in an area. Currently, this shortcut also causes browser's default behavior (all the texts in the page are selected). I haven't found any workaround yet.

(Also, there might be some needs to conditionally apply options. For example, This have been discussed on [this issue](https://github.com/evancz/elm-html/issues/83). I don't need it for now though.)

**Comment by AdrianoFerrari** [comment]
This doesn't directly answer your question, but if you're using a lot of shortcuts in Elm, I found that using Mousetrap.js helps. With it you can override browser defaults, and send key combo strings into Elm via a port ("mod+a" = `(ctrl ||cmd)+a`) to handle there.

**Comment by evancz** [comment]
`onWithOptions` needs to be upgraded to allow conditional use of `stopPropagation` and such, so when that gets upgraded, it seems reasonable to upgrade things here as well. Will try to do before 0.18

**Comment by eriklott** [comment]
I'll be glad to see `onWithOptions` added to the API as well.
