### ISSUE TITLE
Feature Request: Exposing Dom.Size module

### ISSUE THREAD

**Issue by maca** [elm-lang/dom#15]
I would find useful to be able to import Dom.Size, specifically to implement autogrow textarea and dynamic layouts.

Here's an example of an autogrow textaerea implementation using Dom.Size
https://gist.github.com/scottcorgan/49a3c1015a20bfdedd9f4f9f633402f4

**Comment by fbonetti** [comment]
+1. This feature would allow me to build a "[virtual table](https://facebook.github.io/fixed-data-table/)" that only renders visible rows. For example, a table that has 100,000 rows but only renders 20 at a time.

**Comment by MarkNijhof** [comment]
Yes please!

**Comment by KillerX** [comment]
Note that #19 is the related PR.

**Comment by waratuman** [comment]
+1 on this feature as well. Would love to be able to know the height / width of a node.

**Comment by wjdhamilton** [comment]
+1 - please! This would be very handy for me as well!

**Comment by evancz** [comment]
It was not exposed because the API was not right. I talked about particular module a bit in my recent talk called [What is Success?](https://youtu.be/uGlzRt-FYto)

The API that we ended up with is called `getViewport` and is available in the new `elm/browser` package with Elm 0.19
