### ISSUE TITLE
Does not work with elm-test on command line

### ISSUE THREAD

**Issue by gkubisa** [elm-lang/dom#2]
`ReferenceError: document is not defined` `onDocument: F3(on(document)),`

It looks like the error is triggered by accessing the `document` here: https://github.com/elm-lang/dom/blob/0273fabfcc49fda2994ff4da6202b2c4a42c1551/src/Native/Dom.js#L29 A `ReferenceError` would also occur when accessing `window` on the next line.

Simply importing `Dom.LowLevel` into a test file exposes the issue.

It also affects `elm-lang/navigation`, see https://github.com/elm-lang/navigation/issues/7 .

**Comment by evancz** [comment]
Looks like I fixed this a while ago! https://github.com/elm-lang/dom/commit/7ea94b1ee2e7cdfd54bc7cee8e761dba364b31ce

Thanks for the report!
