### ISSUE TITLE
Dom.focus does not raise keyboard in Firefox for Android

### ISSUE THREAD

**Issue by spookylukey** [elm-lang/dom#21]
If you do `.focus()` in Javascript on a text input element in a mobile device, normally the screen keyboard is shown automatically, just like if you focus the element manually.

However, using `Dom.focus` this does not happen in Firefox for Android.

A sample app is here:

https://ellie-app.com/embed/7FD6kr6kba1/1
(Using Elm 0.18)

Further info:

In Firefox for Android, there seems to be a condition that in order for the `.focus()` call to invoke the appearance of the screen keyboard, the call must be done from within an event handler responding to user action, such as a click or tap. (I guess this is a deliberate feature, to stop web pages doing crazy things with keyboards misbehaving, I believe similar logic has been used to prevent certain actions such as lots of popup windows being created etc.).

If the call is from within a callback passed to `setTimeout` or `requestAnimationFrame`, while the text input is focussed as expected, the keyboard does not appear on the screen.

Demo for this behaviour: 

https://codepen.io/spookylukey/full/GyERmL

In my tests Chrome for Android, doesn't show the same behaviour, the keyboard opens in all cases. I haven't tested any other browsers.

I don't know the architecture of Elm well enough, but I'm assuming this problem is due to Elm passing everything through `requestAnimationFrame` or something similar, and that fixing it will basically be impossible.

If so, that's understandable. It could perhaps be documented, or this bug could serve as documentation even if it is closed as WONTFIX.

I have also tried using ports and doing the `.focus()` call in Javascript, but this doesn't work, presumably because that code is also not run from within the call stack of an 'onclick' event handler. (I haven't created a minimal test case for this yet).

**Comment by spookylukey** [comment]
In case the ellie-app/code-pen links rot in the future, here are minimal test cases:

Elm Main.js:

    
    import Html exposing (Html, program, div, input, button, text)
    import Html.Attributes as A
    import Html.Events exposing (onClick)
    import Task
    
    import Dom
    
    main =
      program { 
         init = init, view = view, update = update,
         subscriptions = \m -> Sub.none       
      }
    
    init = (Empty, Cmd.none)
    
    view model =
      div []
        [ input [ A.id "textbox"
                , A.type_ "text"
                ]  []
        
        , button [ onClick FocusIt ] [ text "Focus" ]
        ]
    
    
    type Msg 
        = FocusIt
        | Noop
        
    
    type Model = Empty
    
    update msg model =
      
      case msg of
         FocusIt ->
             (model,  Task.attempt (\_ -> Noop) (Dom.focus "textbox"))
         Noop ->
             (model, Cmd.none) 

Javascript comparison:

    
    <!DOCTYPE html>
    <html lang="en" >
      <body>
        <input type="text" id="textbox">
    
        <p>Direct onclick:
          <button onclick="focusIt()">Focus it</button>
        </p>
        <p>Using setTimeout:
          <button onclick="setTimeout(focusIt, 0)">Focus it</button>
        </p>
        <p>Using requestAnimationFrame:
          <button onclick="requestAnimationFrame(focusIt)">Focus it</button>
        </p>
    
        <script >
         function focusIt (ev) {
             document.getElementById('textbox').focus();
         }
        </script>
      </body>
    </html>

**Comment by spookylukey** [comment]
According to [this comment](https://discourse.elm-lang.org/t/window-confirm-without-native-code/844/3) from Evan, the issue may be fixed in Elm 0.19

**Comment by evancz** [comment]
In 0.19 you can do things synchronously through ports. I think that'll let you do whatever you need to do.
